PiggyProjG/piggy/urls.py
from django.urls import path

from . import views

app_name = 'piggy'

urlpatterns = [
    # example: '/', '/index'
    path('', views.index, name='index'),
    
    # example: '/plans/', a.k.a. project groups
    path('plans/', views.plans, name='plans'),
    path('plan/add/', views.add_plan, name='add_plan'),
    path('plan/<int:plan_id>/', views.plan_detail, name='plan_detail'),
    path('plan/<int:plan_id>/create_team/', views.create_team, name='create_team'),
    path('plan/<int:plan_id>/start/', views.start_plan, name='start_plan'),
    path('plan/<int:plan_id>/stop/', views.stop_plan, name='stop_plan'),
    path('plan/<int:plan_id>/edit/', views.edit_plan, name='edit_plan'),
    path('plan/<int:plan_id>/del/', views.del_plan, name='del_plan'),
    path('plan/<int:plan_id>/add_project/', views.add_project, name='add_project'),
    path('plan/<int:plan_id>/kick/<int:team_id>/', views.kick_out_team, name='kick_out_team'),
    
    # example: '/projects/'
    path('projects/', views.projects, name='projects'),
    path('projects/search/', views.search_projects, name='search_projects'),
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),
    path('project/<int:project_id>/del/', views.del_project, name='del_project'),
    path('project/<int:project_id>/edit/', views.edit_project, name='edit_project'),
    
    # example: '/teacher/'
    path('teachers/', views.teachers, name='teachers'),
    path('teacher/<int:teacher_id>/', views.teacher_detail, name='teacher_detail'),

    # example: '/team/'
    path('team/<int:team_id>/', views.team_detail, name='team_detail'),
    path('team/<int:team_id>/wish/', views.team_wish, name='team_wish'),
    path('team/<int:team_id>/join/', views.join_team, name='join_team'),
    path('team/<int:team_id>/quit/', views.quit_team, name='quit_team'),


    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

PiggyProjG/projg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include('piggy.urls')),
]

PiggyProjG/piggy/models.py
from django.db import models

# Create your models here.

class Teacher(models.Model):
    username = models.CharField(max_length=150)
    password = models.CharField(max_length=128)
    name = models.CharField(max_length=150)
    email = models.CharField(max_length=150)
    resume = models.CharField(max_length=150)

    def __str__(self):
        return "{}".format(self.name, self.username)


class Student(models.Model):
    username = models.CharField(max_length=150)
    password = models.CharField(max_length=128)
    name = models.CharField(max_length=150)
    rank = models.IntegerField(default=0)
    email = models.CharField(max_length=150)
    resume = models.CharField(max_length=150)
    
    def __str__(self):
        return "{}".format(self.name, self.username)


class Plan(models.Model):
    """
    A plan may contain several projects, and is owned by a teacher.
    While a plan is not expired, team in this plan can modify their wishes.
    """
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    is_expired = models.BooleanField(default=False)
    description = models.CharField(max_length=500)

    def __str__(self):
        return "{} ({})".format(self.name, self.teacher)


class Project(models.Model):
    project_group = models.ForeignKey(Plan, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=500)
    max_group_num = models.IntegerField(default=5)
    max_team_member_num = models.IntegerField(default=5)
    
    def __str__(self):
        return "{} in {}".format(self.name, self.project_group)


class Team(models.Model):
    # plan to which this team belong
    project_group = models.ForeignKey(Plan, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    # assigned project
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    members = models.ManyToManyField(Student)

    def __str__(self):
        return "{} @ {}".format(self.name, self.project_group)


class TeamWish(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    # wished project ...
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    # ... with priority
    priority = models.IntegerField()
    
    def __str__(self):
        return "{} #{} {}".format(self.team.name, self.priority, self.project)

PiggyProjG/piggy/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")
		print('jjjjj')

	def save(self, commit=True):
		print('jbb')
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			print('jbbb')
			user.save()
		return user

PiggyProjG/piggy/views.py
# from django.core.checks import messages
from django.db.models.query import QuerySet
from django.db.models import Q
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template import loader
from django.utils import timezone
from django.http import HttpResponse
from django.contrib import messages
from django.views.generic import ListView
import re

import py_eureka_client.eureka_client as eureka_client

from .models import *

def get_user_context(request):
    context = dict()

    try:
        loggedin_user_username = request.session['username']
        role = request.session['role']
        if role == 'student':
            context['uu'] = get_object_or_404(Student, username=loggedin_user_username)
            context['role'] = 'Student'

        elif role == 'professor':
            context['uu'] = get_object_or_404(Teacher, username=loggedin_user_username)
            context['role'] = 'Professor'
    except:
        context['role'] = ''
        context['uu'] = ''
    
    return context


def index(request):
    context = get_user_context(request)

    return render(
        request,
        'piggy/index.html',  # Relative path from the 'templates' folder to the template file
        context
    )


def start_plan(request, plan_id):
    temp = get_object_or_404(Plan, pk=plan_id)
    temp.is_expired = False
    temp.save()
    
    return HttpResponseRedirect('/plan/' + str(plan_id) + '/')
    # return HttpResponseRedirect(request.path_info)


def stop_plan(request, plan_id):
    temp = get_object_or_404(Plan, pk=plan_id)
    temp.is_expired = True
    temp.save()
    
    # Packing data
    projects = Project.objects.filter(project_group=temp)
    teams = Team.objects.filter(project_group_id=plan_id)

    data = dict()
    data['projects'] = [
        {
            'id': proj.id,
            'max_group_num': proj.max_group_num,
        }
        for proj in projects
    ]
    data['wishes'] = []

    for team in teams:
        team_wishes = TeamWish.objects.filter(team=team).order_by('priority')
        data['wishes'].append({
                'team_id': team.id,
                'choices': [ wish.project.id for wish in team_wishes ]
            }
        )
    
    # Data packing finished

    try:
        # Get service / Sending data & Get result
        res = eureka_client.do_service('MyApplication', 'grouping/', data=data, return_type="json")
        print(res)
        # apply grouping result
        # (ranged for loop ensures that only vaild team-project pair will be taken count into)
        for team_id in res.keys():
            the_team = get_object_or_404(Team, pk=team_id)
            the_team.project = get_object_or_404(Project, pk=res[team_id])
            the_team.save()
    except:
        pass
    
    return HttpResponseRedirect('/plan/' + str(plan_id) + '/')


def del_project(request, project_id):
    context = get_user_context(request)
    
    project = get_object_or_404(Project, pk=project_id)
    plan = get_object_or_404(Plan, pk=project.project_group.id)
    if context['role'] == 'Professor' and plan.teacher.id == context['uu'].id:
        project.delete()

    return HttpResponseRedirect('/plan/' + str(plan.id) + '/')
    
    
def del_plan(request, plan_id):
    context = get_user_context(request)

    plan = get_object_or_404(Plan, pk=plan_id)
    if context['role'] == 'Professor' and plan.teacher.id == context['uu'].id:
        plan.delete()
        
    return HttpResponseRedirect('/plans/')

def kick_out_team(request, plan_id, team_id):
    pass


def plans(request):
    context = get_user_context(request)
    
    all_plans = Plan.objects.all()
    context['all_plans'] = all_plans
    return render(
        request, 
        'piggy/plans.html', 
        context
    )


def plan_detail(request, plan_id):
    context = get_user_context(request)
    
    context['plan'] = get_object_or_404(Plan, pk=plan_id)
    context['teams'] = Team.objects.filter(project_group_id=plan_id)
    
    if context['role'] == 'Professor' and context['plan'].teacher.id == context['uu'].id:
        context['flag'] = True

    return render(
        request,
        'piggy/plan_detail.html',
        context
    )


def create_team(request, plan_id):
    context = get_user_context(request)
    
    the_plan = get_object_or_404(Plan, pk=plan_id)
    context['plan'] = the_plan
    
    context['choices'] = context['plan'].project_set.all()
    
    if 'role' in context and context['role'] == 'Student' and not the_plan.is_expired:
        # User must login first, and only student can create team
        # By creating a team under a plan, one also joins in this plan
        # For each plan, students can only join one team 
        # So we must see whether this student is already in a team or not
        already_exist = False
        teams = Team.objects.filter(project_group__id=plan_id)
        for team in teams:
            if context['uu'] in team.members.all():
                already_exist = True
                context['err_msg'] = 'You are already in a team which belongs to this plan.'
                break
        
        # Only when requirements(login & not existed in any team) are satisfied, do post request
        if request.method == "POST" and not already_exist:
            new_team = Team()
            new_team.name = request.POST['team_name']
            project_id = int(request.POST['default_project_id'])
            new_team.project_group = context['plan']
            new_team.project = Project.objects.get(id=project_id)
            new_team.save()
            context['msg'] = 'Team created successfully.'
            new_team.members.add(context['uu'])

    else:
        context['err_msg'] = 'You don\'t have enough permissions.'

    return render(
        request,
        'piggy/create_team.html',
        context,
    )


def join_team(request, team_id):
    context = get_user_context(request)
    the_team = get_object_or_404(Team, pk=team_id)
    the_plan = get_object_or_404(Plan, pk=the_team.project_group.id)
    if 'role' in context and context['role'] == 'Student' and not the_plan.is_expired:
        # User must login first, and only student can join team
        # For each plan, students can only join one team 
        # So we must see whether this student is already in a team or not
        already_exist = False
        teams = Team.objects.filter(project_group__id=the_team.project_group.id)
        for team in teams:
            if context['uu'] in team.members.all():
                already_exist = True
                context['err_msg'] = 'You are already in a team which belongs to this plan.'
                break
        if not already_exist:
            the_team.members.add(context['uu'])
            the_team.save()
    else:
        context['err_msg'] = 'Permission denied.'
    
    return render(
        request,
        'piggy/finish.html',
        context,
    )


def quit_team(request, team_id):
    context = get_user_context(request)
    the_team = get_object_or_404(Team, pk=team_id)
    the_plan = get_object_or_404(Plan, pk=the_team.project_group.id)

    if 'role' in context and context['role'] == 'Student' and not the_plan.is_expired:
        # User must login first, and can only quit from the team they are alreay in
        # So we must see whether this student is already in a team or not
        already_exist = False
        if context['uu'] in the_team.members.all():
            the_team.members.remove(context['uu'])
            the_team.save()
            if len(the_team.members.all()) == 0:
                the_team.delete()
        else:
            context['err_msg'] = 'You don\'t belong to this team.'
    else:
        context['err_msg'] = 'Permission denied.'
    
    return render(
        request,
        'piggy/finish.html',
        context,
    )


def projects(request):
    context = get_user_context(request)
    
    context['all_plans'] = Plan.objects.all()
    return render(
        request,
        'piggy/projects.html',
        context,
    )


def project_detail(request, project_id):
    context = get_user_context(request)
    
    project = get_object_or_404(Project, pk=project_id)
    context['project'] = project
    
    context['plan'] = get_object_or_404(Plan, pk=context['project'].project_group.id)

    if context['role'] == 'Professor' and context['plan'].teacher.id == context['uu'].id:
        context['flag'] = True
            
    return render(
        request, 
        'piggy/project_detail.html', 
        context
    )


def teachers(request):
    context = get_user_context(request)
    
    context['teachers'] = Teacher.objects.all()
    
    return render(
        request,
        'piggy/teachers.html',
        context,
    )


def teacher_detail(request, teacher_id):
    context = get_user_context(request)
    context['teacher'] = get_object_or_404(Teacher, pk=teacher_id)
    context['all_plans'] = Plan.objects.filter(teacher_id=teacher_id)
    
    return render(
        request,
        'piggy/teacher_detail.html',
        context
    )


def team_detail(request, team_id):
    context = get_user_context(request)
    team = get_object_or_404(Team, pk=team_id)
    context['team'] = team
    return render(
        request,
        'piggy/team_detail.html',
        context
    )


def team_wish(request, team_id):
    MAX_WISH_NUM = 3
    # all projects avalaible for current team

    team = get_object_or_404(Team, pk=team_id)
    if request.method == "POST":
        # TO-DO: permission check
        # check if the project is expired
        if team.project_group.is_expired:
            messages.Error('Your plan no longer allow wish modification.')

        for i in range(1, MAX_WISH_NUM + 1):
            key_name = 'wish' + str(i)
            project_id = int(request.POST[key_name])

PiggyProjG/piggy/templates/piggy/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{% block title %}
    <title>Piggy</title>
{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
{% load static %}
    <link rel="stylesheet" href="{% static 'piggy/css/style.css' %}">
    <link rel="icon" href="{% static 'piggy/favicon.svg' %}">
    <link rel="shortcut icon" href="{% static 'piggy/favicon.png' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    {% if uu %}
                    <li>Welcome,<br/><a href="{% url 'piggy:dashboard' %}">{{uu.name}}</a> ({{role}})</li>
                    <li><a href="{% url 'piggy:logout' %}">Logout</a></li>
                    {% else %}
                    <li>
                        <a href="{% url 'piggy:login' %}">Login</a>/
                        <a href=" {% url 'piggy:register' %}">Register</a>
                    </li>
                    {% endif %}
                    <hr/>
                    <li><a href="{% url 'piggy:index' %}">Home</a></li>
                    <li><a href="{% url 'piggy:plans' %}">All Plans</a></li>
                    <li><a href="{% url 'piggy:projects' %}">All Projects</a></li>
                    <li><a href="{% url 'piggy:teachers' %}">All Teachers</a></li>
                    <hr/>
                    <li><a href="{% url 'piggy:search_projects' %}">Search Project</a></li>
                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-9">
            {% block content %}
                <!-- default content text (typically empty) -->
            {% endblock %}
        </div>
    </div>
</div>
</body>

</html>

PiggyProjG/piggy/templates/piggy/base_generic_edit_add.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <title>Piggy</title>
    {% endblock %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'piggy/css/style.css' %}" />
    <link rel="icon" href="{% static 'piggy/favicon.svg' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="shortcut icon" href="{% static 'piggy/favicon.png' %}" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        body {
            background: hsl(213, 13%, 87%);
            background: linear-gradient(to right, #e0e2e5, #dde1e3);
        }
    </style>
  </head>

<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
<div class="container-fluid">
    <a class="navbar-brand" href="{% url 'piggy:index' %}">Piggy</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:plans' %}">Plans</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:projects' %}">Projects</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:teachers' %}">Teachers</a>
            </li>
            <!-- <li class="nav-item"><a class="nav-link" href="{% url 'piggy:search_projects' %}">Search Project</a></li> -->
            <li class="nav-itme">
                <a href="{% url 'piggy:search_projects' %}">
                    <button class="btn btn-primary" type="button">Search</button></a>
            </li>
        </ul>
        <ul class="navbar-nav navbar-right">
            {% if uu %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:dashboard' %}"
                    ><span class="glyphicon glyphicon-user"></span> {{ uu.name}}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:logout' %}"
                    ><span class="glyphicon glyphicon-log-out"></span> Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:login' %}"
                    ><span class="glyphicon glyphicon-log-in"></span>Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'piggy:register' %}"
                    ><span class="glyphicon glyphicon-user"></span>Register</a >
            </li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %} 
            {% endblock %}
        </div>
        <div class="col-sm-8">
            <div class="container-fluid p-5 bg-white">
                {% block content %}

                {% endblock %}
            </div>
          </div>
    </div>
</div>
</body>
</html>

PiggyProjG/piggy/templates/piggy/base_generic_no_content.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <title>Piggy</title>
    {% endblock %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'piggy/css/style.css' %}" />
    <link rel="icon" href="{% static 'piggy/favicon.svg' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="shortcut icon" href="{% static 'piggy/favicon.png' %}" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        body {
            background: hsl(213, 13%, 87%);
            background: linear-gradient(to right, #e0e2e5, #dde1e3);
        }
    </style>
  </head>

<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
<div class="container-fluid">
    <a class="navbar-brand" href="{% url 'piggy:index' %}">Piggy</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:plans' %}">Plans</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:projects' %}">Projects</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:teachers' %}">Teachers</a>
            </li>
            <!-- <li class="nav-item"><a class="nav-link" href="{% url 'piggy:search_projects' %}">Search Project</a></li> -->
            <li class="nav-itme">
                <a href="{% url 'piggy:search_projects' %}">
                    <button class="btn btn-primary" type="button">Search</button></a>
            </li>
        </ul>
        <ul class="navbar-nav navbar-right">
            {% if uu %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:dashboard' %}"
                    ><span class="glyphicon glyphicon-user"></span> {{ uu.name}}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:logout' %}"
                    ><span class="glyphicon glyphicon-log-out"></span> Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'piggy:login' %}"
                    ><span class="glyphicon glyphicon-log-in"></span>Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'piggy:register' %}"
                    ><span class="glyphicon glyphicon-user"></span>Register</a >
            </li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %} 
            {% endblock %}
        </div>
        <div class="col-sm-8">
            <div class="container-fluid p-5 bg-white">
                {% block content %}

                {% endblock %}
            </div>
          </div>
    </div>
</div>
</body>
</html>

PiggyProjG/piggy/templates/piggy/plan_detail.html
{% extends "piggy/base_generic_no_content.html" %}

{% block title %}
    <title>{{ plan.name }} - Plan's details</title>
{% endblock %}

{% block content %}
    <h1 class="h1"> {{ plan.name }} </h1>
    <table class="table table-hover">
        <thead></thead>
        <tbody>
            <tr>
                <th class="h5">Professor:</th>
                <td>{{ plan.teacher }} <a href="{% url 'piggy:teacher_detail' plan.teacher.id %}"><i class="bi bi-info-circle-fill"></i></a></td>
            </tr>
            <tr>
                <th class="h5">Status:</th>
                <td>
                    {% if plan.is_expired %}
                        Expired
                        {% if flag %}
                            <a href="{% url 'piggy:start_plan' plan.id %}">Start plan</a>
                        {% endif %}
                    {% else %}
                        Running
                        {% if flag %}
                            <a href="{% url 'piggy:stop_plan' plan.id %}">Stop plan</a>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th class="h5">Description:</th>
                <td>{{ plan.description }} </td>
            </tr>
            <tr>
                <th class="h5">
                    Included Projects
                    <!-- {% if flag %}
                        <a class="btn btn-success btn-sm" href="{% url 'piggy:add_project' plan.id %}"><i class="bi bi-plus-lg"></i></a>
                    {% endif %} -->
                </th>
                <td>
                    <div class="list-group">
                        {% for project in plan.project_set.all %}
                            <a class="list-group-item list-group-item-action" href="{% url 'piggy:project_detail' project.id %}">
                                <div class="d-flex w-100 justify-content-between">
                                    <h6 class="mb-1">
                                        {{ project.name }}
                                    </h6>
                                    <!-- {% if flag %}
                                        <button type="button" class="btn-close" href="{% url 'piggy:del_project' project.id %}"></button>
                                    {% endif %} -->
                                </div>
                                <p class="mb-1">
                                    <small>{{ project.description }}</small>
                                </p>
                            </a>
                        {% endfor %}
                    </div>
                </td>
            </tr>
            <tr>
                <td class="h5">Included teams:</td>
                <td>
                    <div class="list-group">
                        {% for team in teams %}
                            <a class="list-group-item list-group-item-action" href="{% url 'piggy:team_detail' team.id %}">
                                <div class="d-flex w-100 justify-content-between">
                                    <h6 class="mb-1">
                                        {{ team.name }}
                                    </h6>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    {% if role == 'Student' %}
        <a class="btn btn-success" href="{% url 'piggy:create_team' plan.id %}">Create a Team</a>
    {% endif %}
    {% if flag %}
        <a class="btn btn-primary" href="{% url 'piggy:edit_plan' plan.id %}">Edit Plan</a>
    {% endif %}
    
{% endblock %}

PiggyProjG/piggy/templates/piggy/team.html
{% extends "piggy/base_generic.html" %}

{% block title %}
    <title> {{ team.name }} </title>
{% endblock title %}

{% block content %}
    <h1> {{ team.name }} </h1>
    <!-- <p> {{ team.name }} belongs to {{ team.project_group }}</p> -->
    <h3> Chosen Project </h3>
        <p> {{ team.name }} has project 
            <a href="{% url 'piggy:project_detail' team.project.id %}" >{{ team.project.name }}</a>
            in 
            <a href="{% url 'piggy:plan_detail' team.project_group.id %}"> {{ team.project_group.name }} </a>
            directed by Prof 
            <a href="{% url 'piggy:teacher_detail' team.project_group.teacher.id %}">{{ team.project_group.teacher.name }}</a>
        </p>
    <h3> Team Member </h3>
        <p> {{ team.name }} has team members below:</p>
        <ul>
            {% for member in team.members.all %}
                <li> {{ member }} </li>
            {% endfor %}
        </ul>
{% endblock content %}